### PR TITLE
Allow to use jsx

### LINKED ISSUE #12: Support JSX ?
Hi, i wonder if it's possible to use JSX in the source code.
This is a test repo : https://github.com/wcastand/test-microbundle
I have a small repo to test it out and right now i get an error from nodent : 

```bash
▲ test-microbundle at master ✔ yarn build
yarn run v1.3.2
$ microbundle --jsx
SyntaxError: Unexpected token (4:2) /Users/willoo/Documents/Projects/test-microbundle/src/index.js (nodent)
  <div>
--^
✨  Done in 0.50s.
```

In the source code you have an options for jsx in buble `options.jsx` but nodent is before buble.

### PR DESCRIPTION
**Pull request by wcastand**
add acorn-jsx as a dependency and allow nodent to handle jsx.

Fix #12

### CODE REVIEW

**Comment by developit** [comment]
Are you able to verify that this works locally?

**Comment by wcastand** [comment]
i tested it locally with yarn link on my test project and it built the project without error.
But i did not test my bundled packages in an app once it was built.

**Comment by developit** [comment]
awesome!

**Comment by alexindigo** [comment]
@developit has it been released? I couldn't make it work with jsx.

**Pull request merged**
