### PR TITLE
Release 0.12

### PR DESCRIPTION
**Pull request by ForsakenHarmony**

### CODE REVIEW

**Comment by dai-shi** [comment]
Hi! I'm getting an error installing v0.12.0-next.7 on MacOS.

```bash
$ mkdir /tmp/test
$ cd /tmp/test
$ npm init -y
$ npm install -D microbundle@0.12.0-next.7

npm WARN test@1.0.0 No description
npm WARN test@1.0.0 No repository field.

npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /private/tmp/test/node_modules/microbundle/dist\cli.js
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/private/tmp/test/node_modules/microbundle/dist\cli.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
```

v0.12.0-next.6 doesn't have this issue. Hope it helps.

**Comment by kristoferbaxter** [comment]
@dai-shi I was unable to reproduce this with `yarn`, what version of `npm` are you using?

**Comment by dai-shi** [comment]
```bash
$ npm -v
6.13.0
```

Let me try with yarn. --- Yeah, it works.

Now, updating npm `6.13.4` fixes it. So, it was an npm issue. Resolved.
Sorry for the mess. Thanks for your time!

**Comment by kristoferbaxter** [comment]
No worries @dai-shi, glad we got to the bottom of it!

**Comment by snapwich** [comment]
@kristoferbaxter , I have this same issue, `0.12.0-next.7` is broken with a pretty recent version of npm, `6.12.0`. Updating isn't a possibility in the CI environment and `0.12.0-next.7` breaks on `npm install`, so I've had to pin on `0.12.0-next.6` to fix CI.

`verbose stack Error: ENOENT: no such file or directory, chmod '~/code/rssp-ui/packages/rssp-client-api-js/node_modules/microbundle/dist\cli.js'`

I notice there is an incorrect backslash file separator in there, I'm guessing that is what is causing the issue? I'm not sure where it is coming from though.

**Comment by kristoferbaxter** [comment]
We believe this to be a bug in npm, but let’s take a look at the delta between .6 and .7 for a potential workaround.

**Comment by ForsakenHarmony** [comment]
was supposed to be the last pr to rleease stable 0.12 but alright

**Pull request merged**
