### PR TITLE
fix: properly forward `jsx` and `jsxPragma` to `customBabel`

### PR DESCRIPTION
**Pull request by FezVrasta**

### CODE REVIEW

**Comment by FezVrasta** [comment]
@ForsakenHarmony 🙏?

**Comment by FezVrasta** [comment]
Is anything else needed on my side or could we get this merged and released?

Also, do we have any roadmap for the 0.12 stable release?

Thanks!

**Comment by ForsakenHarmony** [comment]
sorry, I merged master into this and then switched to some other tab 🙈

**Comment by ForsakenHarmony** [comment]
Not sure if there are any blockers rn, mostly trying to see if there any issues with babel or regressions that came from the switch

**Comment by FezVrasta** [comment]
I know I'm being a PITA and I'm sorry, but may you release a next.5 with this fix? 🙏

**Comment by ForsakenHarmony** [comment]
done, sorry 🙃

**Pull request merged**
