### PR TITLE
Strip comments from output

### PR DESCRIPTION
**Pull request by developit**

### CODE REVIEW

**Comment by developit** [comment]
@marvinhagemeister Ideally I would like to extract license comments into a file if they need to be preserved.

**Comment by jnordberg** [comment]
I'd love to see this merged, half my bundle is a microsoft license comment from something

**Comment by marvinhagemeister** [comment]
@developit I have no permissions to check the GH actions result. Not sure why it's stuck.

**Comment by developit** [comment]
Waiting on PR approval :P

**Pull request merged**
