### PR TITLE
Migrate to gh actions

### PR DESCRIPTION
**Pull request by JoviDeCroock**
I tried it out for `Preact` and `Preact-cli` so thought about giving it a shot here as well

### CODE REVIEW

**Comment by JoviDeCroock** [comment]
```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main resolved in /home/runner/work/microbundle/microbundle/node_modules/@babel/helper-compilation-targets/package.json
    at applyExports (internal/modules/cjs/loader.js:524:9)
    at resolveExports (internal/modules/cjs/loader.js:541:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:661:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:963:27)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/runner/work/microbundle/microbundle/node_modules/@babel/preset-env/lib/debug.js:8:33)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Module._compile (/home/runner/work/microbundle/microbundle/node_modules/pirates/lib/index.js:99:24) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

**Comment by JoviDeCroock** [comment]
Might have to write an action to replace this https://github.com/GoogleChromeLabs/travis-size-report#readme

**Comment by ForsakenHarmony** [comment]
#549 🙃

**Comment by JoviDeCroock** [comment]
@ForsakenHarmony WHOOPS :p sorry about that

**Pull request closed without merging**
