### PR TITLE
Fix auto installing buggy @rollup/plugin-commonjs - v1.11.0

### PR DESCRIPTION
**Pull request by mihilranathunga**
resolves rollup/plugins#304

### CODE REVIEW

**Comment by marvinhagemeister** [comment]
Looks like a new version of that plugin is out [which includes the fix](https://github.com/rollup/plugins/compare/babel-v5.0.2...commonjs-v12.0.0)  for the linked issue. I think instead of limiting the install range it'd be better if we just upgrade to that. What do you think?

**Comment by developit** [comment]
I agree with upgrading to 12, though I believe it still has some of the issues present in 11.1.

**Comment by mihilranathunga** [comment]
yes please, upgrade to the latest. Will close this.

**Comment by jakewies** [comment]
This is still an issue for me. It looks like `microbundle` [is still installing buggy `@rollup/plugin-commonjs` v11.1.0](https://github.com/developit/microbundle/blob/master/package.json#L77).

**Comment by marvinhagemeister** [comment]
@jakewies Looks like there hasn't been a release published since the fix was merged.

@developit Should we cut a new release?

**Comment by developit** [comment]
Yup - just published [0.12.1](https://github.com/developit/microbundle/releases/tag/0.12.1) with this fix!

**Comment by jakewies** [comment]
@developit @marvinhagemeister not sure if [0.12.1](https://github.com/developit/microbundle/releases/tag/0.12.1) included this fix. Am I missing something? 😅

**Comment by developit** [comment]
Fix incoming, apologies.

**Comment by jakewies** [comment]
No worries!

**Pull request closed without merging**
