### PR TITLE
Dev Branch

### PR DESCRIPTION
**Pull request by ForsakenHarmony**

### CODE REVIEW

**Comment by ForsakenHarmony** [comment]
For the comments https://github.com/terser-js/terser/issues/353

**Comment by ForsakenHarmony** [comment]
made the dev branch bc no permission to push to master 🙃

**Comment by wardpeet** [comment]
@ForsakenHarmony thanks for fixing my bugs! <3

**Comment by ForsakenHarmony** [comment]
well I didn't realise they were there until I ran into them 🙃

**Pull request merged**
