### PR TITLE
Only generate types when requested

### PR DESCRIPTION
**Pull request by marvinhagemeister**
This PR changes the default behaviour to only generate types when the `types` or `typings` field was found in `package.json`.

Replaces #589 .

### CODE REVIEW

**Comment by ForsakenHarmony** [comment]
This seems to kinda be the inverse of #589?

**Comment by developit** [comment]
I think this needs the [`emitDeclaration` tweak](https://github.com/developit/microbundle/pull/589/files#diff-1fdf421c05c1140f6d71444ea2b27638R557) from #589 - currently if there are no `.ts` files, the typescript rollup plugin doesn't get run. Also the allowJs bit (though that could perhaps be on-by-default).

**Comment by marvinhagemeister** [comment]
True, looks like I misunderstood the original PR 🙈

**Comment by developit** [comment]
lol not at all, I'll try to make this change there

**Pull request closed without merging**
