### PR TITLE
adding ts support

### PR DESCRIPTION
**Pull request by tymondesigns**
refs #5 

had a quick stab at it yesterday, although getting an error when running the cli:

image

Any thoughts? @developit

### CODE REVIEW

**Comment by developit** [comment]
Funky - looking into this today.

**Comment by LinusU** [comment]
Will this also put a `.d.ts` file in the published package? That seems like something that we should absolutely do...

**Comment by developit** [comment]
@LinusU - think it would make sense to disable the `flow` and `buble` plugins when ts is enabled? We'd just need to tell it to transpile to ES5, but I think that'd garner better output.

**Comment by LinusU** [comment]
Yeah, I think so, TS can compile with ES5 as output, and will then handle ES6/7/etc. syntax

**Comment by gpoitch** [comment]
You could probably drop `buble` completely and have typescript transpile the `.js` files

**Comment by LinusU** [comment]
> Too weird? haha

I like it! 🚀

**Comment by developit** [comment]
@gpoitch I think that would increase output size quite a bit though

**Comment by KatSick** [comment]
@developit is ther any updates on this ?

**Comment by developit** [comment]
Might be worth trying out Babel's typescript support if we switch to Babel.

**Comment by marvinhagemeister** [comment]
Babelsberg TypeScript support is limited in the sense that things like ```const enums``` is not supported. Only the TypeScript compiler has the full feature set for now.

**Comment by tymondesigns** [comment]
It now runs the build and outputs the compiled ts files to dist 🎉  

However getting an annoying output on the console:
image

**Comment by tymondesigns** [comment]
all good now I think @developit

**Comment by tymondesigns** [comment]
🎉

**Pull request merged**
