### PR TITLE
Fix #849 : Add dependabot for NPM and Github Actions

### LINKED ISSUE #849: Add dependabot
To ease and fasten dependency update, use [Dependabot](https://github.com/dependabot/dependabot-core) like [here](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/enabling-and-disabling-version-updates#example-dependabotyml-file).

### PR DESCRIPTION
**Pull request by emibcn**
To ease and fasten dependency update, use [Dependabot](https://github.com/dependabot/dependabot-core) like [here](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/enabling-and-disabling-version-updates#example-dependabotyml-file).

### CODE REVIEW

**Comment by rschristian** [comment]
Dependabot is super spammy and pretty rarely useful in my experience. Don't think it's needed or that it adds anything of value here.

**Comment by emibcn** [comment]
I have a security alert which cannot be resolved because microbundle-crl depends on it:

image

**Comment by rschristian** [comment]
Microbundle-crl is forked version of Microbundle. They're separate packages. You can find [its repo here](https://github.com/transitive-bullshit/microbundle) though the author has disabled issues it looks like.

**Comment by emibcn** [comment]
Whooops... Sorry. Its source code URL points here.

**Pull request closed without merging**
