### PR TITLE
Add ability to include node built-in modules as external dependencies

### PR DESCRIPTION
**Pull request by krismuniz**
Hello 👋

This PR adds the ability to include node built-in modules as external dependencies by specifying `--external natives`

> Related to https://github.com/developit/microbundle/issues/288, but I'm not 100% sure if it closes it, as the PR suggests using the `rollup-plugin-node-builtins` plugin for resolving these dependencies and including shims where necessary (i.e. in the browser).

### Problem

When using `microbundle` for building node modules (`--target node`), you have to include every built-in module like this:

```shell
microbundle --external events,util,child_process
```

This becomes even more tedious when a built-in module uses _other_ built-in modules.

As @lukeed suggests in [this comment](https://github.com/developit/microbundle/issues/288#issuecomment-449825403), it would be nice to have the option to simply treat all built-in node modules as external dependencies by adding `--external natives` instead of `--external events,util,child_process[, ...]`. 

### Solution

Add all modules from `require('module').builtinModules` to the list of external dependencies like this:

```shell
microbundle --external natives
```

### Feedback Welcome

 ✏️Let me know if you need any changes
🗯If this is not ideal, what would be a nice alternative to specifying all built-in modules?

### CODE REVIEW

**Comment by lukeed** [comment]
> Something like this, right?

Correct!

The only other thing to consider here is that `require('module').builtinModules` doesn't work in Node 4.x – hence my two-part suggestion in the original issue. I don't know/can't remember the minimum supported Node version `microbundle` is targeting.

**Comment by Andarist** [comment]
I also agree that this should be the default with node as target, we could use this static list for this - https://github.com/sindresorhus/builtin-modules/blob/master/builtin-modules.json

**Comment by lukeed** [comment]
Don't think we need an extra dependency – the list is built-in to Node in all versions:

```js
require('module').builtinModules || Object.keys(process.binding('natives'))
```

**Comment by krismuniz** [comment]
Right! So if we want Node 4.x support we'd do something like this:

```diff
- let external = require('module').builtinModules.concat(/* ... */);
+ const builtinModules = require('module').builtinModules || Object.keys(process.binding('natives'));
/* ... */
+ builtinModules.concat(/* ... */)
```

**Comment by developit** [comment]
@krismuniz it should only apply to `target==='node'` yup.

**Comment by ianstormtaylor** [comment]
Any news on this? This would be super helpful.

**Comment by ForsakenHarmony** [comment]
Problems mentioned above would have to be solved

**Comment by developit** [comment]
FWIW this behavior is already enabled by default in `microbundle@next`, since `rollup-plugin-node-resolve` handles it by default. I've opened #591 to silence the warnings.

**Pull request closed without merging**
