### PR TITLE
Migrate to terser from uglify-js

### LINKED ISSUE #134: Consider migrating to rollup-plugin-terser
`terser` is a new fork of `uglify-es` and the owner's intention is to maintain it, while `uglify-es` (used by our current used version of `rollup-plugin-uglify`) gets deprecated. 

I think it's the right choice to migrate as `terser` handles es6+ syntax.

### PR DESCRIPTION
**Pull request by Andarist**
fixes #134 

~need to first merge #136 and rebase this one on top of that~

### CODE REVIEW

**Comment by developit** [comment]
I keep getting bit by Uglify's broken function inlining, which I think is addressed in Terser. Kinda want to try this.

**Comment by Andarist** [comment]
Let's merge it in and see how it plays out. Terser is just a continuation of `uglify-es` (same codebase).

**Comment by developit** [comment]
I keep meaning to run this against some projects and check for size differences before/after.  For me, the `mangle.json` is extremely important (the whole purpose of this bundler tbh), so I want to make sure that keeps working.

**Comment by Andarist** [comment]
Well, there shouldnt be any rly noticeable size changes because this is uglifyjs, just its maintained fork rather than unmaintained one.

> mangle.json

From what i remember thanks to this uglify/terser can reproduce mangled identifiers reliably. Whats the use case for this?

**Comment by developit** [comment]
`mangle.json` isn't for cross-build reliability, it's for static property mappings. You can see what Preact uses this for here:
https://github.com/developit/preact/blob/master/config/properties.json

Essentially, `_properties` are mapped to static names which we treat as private (but still exported and available) API.

**Comment by matthewmueller** [comment]
Oh woops, just saw this. This PR would also fix #201. I accidentally PRed the fix as well in #202

**Comment by ForsakenHarmony** [comment]
is there anything blocking this?

to me it seems like this is a drop in replacement with the same features

**Comment by developit** [comment]
No blockers, I think we can merge.

**Comment by developit** [comment]
I'll merge this weekend. 

@matthewmueller agreed on your note in #202 about actually executing the outputs. We should be able to at least automatically verify the module exports are deep equal to the source's.

**Comment by developit** [comment]
Note: looks like sizes went up? (or at least changed). Might be good to double check what the output looks like with Terser.

**Comment by ForsakenHarmony** [comment]
👀

**Comment by ForsakenHarmony** [comment]
And the tsx fixture wraps the iife in () now

**Comment by ForsakenHarmony** [comment]
I think it's fine

**Comment by developit** [comment]
lol it's literally one semicolon?

**Comment by matthewmueller** [comment]
suhweet!

**Pull request merged**
