### PR TITLE
fix: add generateTypes cli option, check false value correctly

### LINKED ISSUE #829: `generateTypes` is not available in cli, and `generateTypes: false` is not woking
https://github.com/developit/microbundle/blob/master/src/index.js#L369

I'll raise a PR to fix it.

### PR DESCRIPTION
**Pull request by JounQin**
close #829

### CODE REVIEW

**Comment by JounQin** [comment]
@developit Any time to review?

**Comment by rschristian** [comment]
What's the use case for this? 

As `types` and `typings` are the only standardized keys for TS types, I can't see why you'd want to generate types without having those keys present? Right now I'd say it would make more sense to go the other way, and remove `generateTypes`, though perhaps I'm not seeing a certain use case?

**Comment by JounQin** [comment]
@rschristian We want to write the `types`file manually.

**Comment by rschristian** [comment]
Ah, yeah, that makes sense.

**Comment by JounQin** [comment]
friendly ping @developit

**Comment by JounQin** [comment]
friendly ping @developit

**Review by developit — APPROVED** [review]

**Comment by developit** [comment]
Ran into this exact issue yesterday, and your PR seems to be the right fix! Thanks.

**Pull request merged**
