### PR TITLE
+ Nodent link in Readme

### PR DESCRIPTION
**Pull request by tomByrer**
I'm assuming you meant that Nodent?

Thanks for all your good work!

### CODE REVIEW

**Comment by developit** [comment]
We did! though actually now that you mention it, we've since switched to @rpetrich's wonderful [babel-plugin-transform-async-to-promises](https://github.com/rpetrich/babel-plugin-transform-async-to-promises)

**Comment by developit** [comment]
amended this PR - let me know if that's okay!

**Comment by ForsakenHarmony** [comment]
shouldn't it be at the bottom of the readme like buble?

**Comment by developit** [comment]
yup, moved to bottom.

**Pull request merged**
