### PR TITLE
wrap brotli in try/catch to avoid error for lower versions of node

### PR DESCRIPTION
**Pull request by madalynrose**
Addresses #487 by catching any error for `brotliSize` and not displaying stats for brotli.

### CODE REVIEW

**Comment by developit** [comment]
Since master tests are failing I'm going to merge this.

**Comment by developit** [comment]
Thanks so much @madalynrose! We'll get an update published ASAP so Gatsby can switch back to the main Microbundle package.

**Comment by ForsakenHarmony** [comment]
Really sorry it took so long, it's in 0.12.0-next.7

0.12 should be out soon as well

**Pull request merged**
