### PR TITLE
Updated rollup to 0.60.1, made code changes to support it

### PR DESCRIPTION
**Pull request by Andarist**
closes #146

Still have to figure out what's going with .ts/.tsx tests, because they are failing - but I'v fixed rest of them for now.

### CODE REVIEW

**Comment by Andarist** [comment]
Ok... tests passing. That is unexpected 😂 as mentioned 2 of them were failing on my machine. Need to investigate this.

**Comment by ForsakenHarmony** [comment]
I've found the tests to be inconsistent as well, the size tests that is

**Comment by developit** [comment]
LGTM.

The size tests are inconsistent with dep upgrades for a reason ;)

**Comment by Andarist** [comment]
> The size tests fail with dep upgrades for a reason ;) it's important to know when things get messed up (because buble got updated, etc)

Sure thing, but this branch was failing on me locally - and I had a fresh install of deps. Hadnt yet time to go back to this to double check.

**Pull request merged**
